[2024-09-13 00:21:35,740]^;INFO^;190^;configuration.py^;get_training_pipeline_config()^;Training pipeline config: TrainingPipelineConfig(artifact_dir='C:\\Users\\prash\\Downloads\\Housing_mlops\\housing\\artifact')
[2024-09-13 00:21:36,285]^;INFO^;190^;configuration.py^;get_training_pipeline_config()^;Training pipeline config: TrainingPipelineConfig(artifact_dir='C:\\Users\\prash\\Downloads\\Housing_mlops\\housing\\artifact')
[2024-09-13 00:21:36,453]^;INFO^;224^;_internal.py^;_log()^;[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-13 00:21:36,453]^;INFO^;224^;_internal.py^;_log()^;[33mPress CTRL+C to quit[0m
[2024-09-13 00:21:50,516]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:21:50] "GET / HTTP/1.1" 200 -
[2024-09-13 00:21:50,606]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:21:50] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:21:52,264]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:21:52] "GET /predict HTTP/1.1" 200 -
[2024-09-13 00:21:52,298]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:21:52] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:22:09,674]^;ERROR^;1745^;app.py^;log_exception()^;Exception on /predict [POST]
Traceback (most recent call last):
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "main12.py", line 76, in predict
    housing_df=HousingData.get_housing_input_data_frame(data)
AttributeError: type object 'HousingData' has no attribute 'get_housing_input_data_frame'
[2024-09-13 00:22:09,679]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:22:09] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2024-09-13 00:24:49,041]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:24:49] "[33mGET /logs HTTP/1.1[0m" 404 -
[2024-09-13 00:25:13,955]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:13] "[33mGET /update_model_config HTTP/1.1[0m" 404 -
[2024-09-13 00:25:17,171]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:17] "[33mGET /train HTTP/1.1[0m" 404 -
[2024-09-13 00:25:37,755]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:37] "GET / HTTP/1.1" 200 -
[2024-09-13 00:25:37,790]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:37] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:25:44,844]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:44] "GET /predict HTTP/1.1" 200 -
[2024-09-13 00:25:44,876]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:44] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:25:46,905]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:46] "GET /predict HTTP/1.1" 200 -
[2024-09-13 00:25:46,927]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:46] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:25:47,971]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:47] "GET /predict HTTP/1.1" 200 -
[2024-09-13 00:25:47,992]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:47] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:25:49,805]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:25:49] "[33mGET /logs HTTP/1.1[0m" 404 -
