[2024-09-13 00:17:32,027]^;INFO^;190^;configuration.py^;get_training_pipeline_config()^;Training pipeline config: TrainingPipelineConfig(artifact_dir='C:\\Users\\prash\\Downloads\\Housing_mlops\\housing\\artifact')
[2024-09-13 00:17:32,813]^;INFO^;190^;configuration.py^;get_training_pipeline_config()^;Training pipeline config: TrainingPipelineConfig(artifact_dir='C:\\Users\\prash\\Downloads\\Housing_mlops\\housing\\artifact')
[2024-09-13 00:17:32,979]^;INFO^;224^;_internal.py^;_log()^;[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-13 00:17:32,979]^;INFO^;224^;_internal.py^;_log()^;[33mPress CTRL+C to quit[0m
[2024-09-13 00:17:41,941]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:17:41] "GET / HTTP/1.1" 200 -
[2024-09-13 00:17:41,994]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:17:41] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:17:43,748]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:17:43] "GET /predict HTTP/1.1" 200 -
[2024-09-13 00:17:43,795]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:17:43] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2024-09-13 00:17:59,374]^;ERROR^;1745^;app.py^;log_exception()^;Exception on /predict [POST]
Traceback (most recent call last):
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\prash\Downloads\Housing_mlops\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "main12.py", line 74, in predict
    housing_df=HousingData.get_housing_input_data_frame(data)
AttributeError: type object 'HousingData' has no attribute 'get_housing_input_data_frame'
[2024-09-13 00:17:59,379]^;INFO^;224^;_internal.py^;_log()^;127.0.0.1 - - [13/Sep/2024 00:17:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
